# General Jekyll Config
highlighter: pygments
url: http://example.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

paginate: 25

markdown: kramdown
redcarpet:
  extensions: ["strikethrough"]